platform :ios, '10.0'

use_frameworks!
inhibit_all_warnings!

workspace 'Template.xcworkspace'

project 'Template.xcodeproj'
project 'TemplateCore/TemplateCore.xcodeproj'
project 'TemplateShared/TemplateShared.xcodeproj'

def common_pods
  # iOS Base Template
  pod 'SwiftLint'
  pod 'Kingfisher'
  pod 'DeviceKit'
  pod 'KeychainAccess'
end

# --------------
# Template app
# --------------
target 'Template' do
  inherit! :search_paths
  project 'Template.xcodeproj'
  common_pods
end

#target 'Template Stage' do
#  inherit! :search_paths
#  project 'Template/Template.xcodeproj'
#  common_pods
#end

# --------------
# TemplateCore
# --------------
target 'TemplateCore' do
  inherit! :search_paths
  project 'TemplateCore/TemplateCore.xcodeproj'
  common_pods
end

# --------------
# TemplateShared
# --------------
target 'TemplateShared' do
  inherit! :search_paths
  project 'TemplateShared/TemplateShared.xcodeproj'
  common_pods
end
